---
title: "Public Health 490Z - Group H"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
###import all useful libraries 
library(tidyverse)
library(readxl)
library(stringr)
library(dplyr)
library(readr)
library(ggplot2)
library(ggrepel)
```

```{r}
###import dataset and a summary
CA_all_data <- read_excel("Desktop/This is Statistics Fall Data Challenge 2021 Dataset_ Food Access Research Atlas Data 2019-ASAFDC 2021.xlsx", sheet = 8)
summary(CA_all_data)
```

```{r}
### Percentage of urban (0 or 1)
df <- CA_all_data %>%
  group_by(Urban) %>%
  count() %>%
  ungroup() %>%
  mutate(pctg = `n` / sum(`n`)) %>%
  arrange(pctg) %>%
  mutate(labels = scales::percent(pctg))
  
  ggplot(df, aes(x = "", 
                 y = pctg, 
                 fill = Urban)) + 
                 geom_col() + 
                 geom_label_repel(aes(label = labels),
                                  posi = position_stack(vjust = 0.1),
                                  show.legend = FALSE) +
                 coord_polar(theta = "y")
df <- CA_all_data
cor(df$Urban, df$LowIncomeTracts)
```

```{r}
### Poverty rate summary with histogram, population in 2010 and poverty rate
df <- CA_all_data
summary(df$PovertyRate)
hist(df$PovertyRate, freq=FALSE, breaks=100)
plot(df$Pop2010, df$PovertyRate)
```

```{r}
### LowIncomeTracts (0 or 1)
df <- CA_all_data %>%
  group_by(LowIncomeTracts) %>%
  count() %>%
  ungroup() %>%
  mutate(pctg = `n` / sum(`n`)) %>%
  arrange(pctg) %>%
  mutate(labels = scales::percent(pctg))
  
  ggplot(df, aes(x = "", 
                 y = pctg, 
                 fill = LowIncomeTracts)) + 
                 geom_col() + 
                 geom_label_repel(aes(label = labels),
                                  posi = position_stack(vjust = 0.1),
                                  show.legend = FALSE) +
                 coord_polar(theta = "y")
```

```{r}
### HUNVFlag (0 or 1)
df <- CA_all_data %>%
  group_by(HUNVFlag) %>%
  count() %>%
  ungroup() %>%
  mutate(pctg = `n` / sum(`n`)) %>%
  arrange(pctg) %>%
  mutate(labels = scales::percent(pctg))
  
  ggplot(df, aes(x = "", 
                 y = pctg, 
                 fill = HUNVFlag)) + 
                 geom_col() + 
                 geom_label_repel(aes(label = labels),
                                  posi = position_stack(vjust = 0.1),
                                  show.legend = FALSE) +
                 coord_polar(theta = "y")
```

```{r}
df <- CA_all_data
hist(df$TractSNAP)
hist(df$TractHUNV)
plot(df$TractSNAP, df$TractHUNV)
cor(df$TractSNAP, df$LowIncomeTracts)
cor(df$TractHUNV, df$LowIncomeTracts)
```



